ALTER TABLE Post ADD COLUMN type VARCHAR(255) NOT NULL DEFAULT 'client';
ALTER TABLE Post ADD COLUMN parentPostId VARCHAR(36);

ALTER TABLE PostCategory ADD COLUMN quantity INT NOT NULL DEFAULT 1;
ALTER TABLE PostCategory ADD COLUMN filledCount INT NOT NULL DEFAULT 0;
ALTER TABLE PostCategory ADD COLUMN roleDescription TEXT;