name: CI/CD para HomeFix (Node + React + TS)

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Descargar código del repositorio
      uses: actions/checkout@v4

    - name: Configurar Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'

    - name: Instalar dependencias
      run: npm ci

    - name: Validar y Compilar TypeScript
      run: npm run build --if-present
        
    - name: Ejecutar Pruebas Unitarias
      run: npm test --if-present

  deploy:
    needs: build-and-test
    if: github.ref == 'refs/heads/develop' && github.event_name == 'push'
    runs-on: ubuntu-latest

    steps:
    - name: Desplegar la aplicación
      run: |
        echo "Aquí van tus comandos de despliegue."
